AWSTemplateFormatVersion: "2010-09-09"
Description: PernApp Resource Stack
Resources:
#Setup EC2 instance and install  AWS code deploy agent
  Ec2Instance: 
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-0bb84b8ffd87024d8" 
      InstanceType: t2.micro
      IamInstanceProfile: !Ref Ec2InstanceProfile
      SecurityGroups:
        - !Ref AppSg
#RSA key already created
      KeyName: conne
      Tags:
        - Key: name
          Value: PernAppInstance
      UserData: 
        Fn::Base64: |
             #! /bin/bash
                sudo yum update
                sudo yum install npm -y
                sudo yum install ruby -y
                sudo yum install wget -y
                cd ~/ec2-user
                sudo wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install
                sudo chmod 100 ./install
                sudo ./install auto
                sudo systemctl start codedeploy-agent
 
# Security Group for EC2 Instance
  AppSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: appsg
      GroupDescription: Security group for MyEC2Instance
# Allow SSH  and HTTPs access from anywhere 
      SecurityGroupIngress:
        - FromPort: 22
          ToPort: 22
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0  

        - FromPort: 443
          ToPort: 443
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0

# Creating Instance Profile for EC2
  Ec2InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Roles: [!Ref AssignIamRoleToOIDC]

#Setup OIDC Trust for AWS with github as the OIDC Provider
  GitHubOIDC:
    Type: "AWS::IAM::OIDCProvider"
    Properties:
      ClientIdList: ["sts.amazonaws.com"]
      Url: "https://token.actions.githubusercontent.com"
      ThumbprintList: [1B511ABEAD59C6CE207077C0BF0E0043B1382612]

#Assign aim Role to GithubOIDC
  AssignIamRoleToOIDC:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Federated: !GetAtt GitHubOIDC.Arn
          Action: sts:AssumeRoleWithWebIdentity
          Condition:
            StringLike:
              token.actions.githubusercontent.com:sub: repo:yankeygilbert/ALFPHA:*
            StringEquals:
              token.actions.githubusercontent.com:aud: sts.amazonaws.com
      Policies:
        - PolicyName: CDPL
          PolicyDocument: 
            Version: '2012-10-17'
            Statement:
            - Action:
              - codedeploy:Batch*
              - codedeploy:CreateDeployment
              - codedeploy:Get*
              - codedeploy:List*
              - codedeploy:RegisterApplicationRevision
              Effect: Allow
              Resource: "*"
      MaxSessionDuration: 3600

#Role for Aws Code Deploy              
  codedeployRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service:
            - codedeploy.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: CDAPL
          PolicyDocument: 
            Version: '2012-10-17'
            Statement:
            - Action:
              - ec2:*
              Effect: Allow
              Resource: "*"

#Creating CodeDeploy Configurations (codedeploy app and deploymentGroup).
  CodeDeployApplication:
    Type: "AWS::CodeDeploy::Application"
    Properties:
      ApplicationName: PernApp
      ComputePlatform: Server
    
  CodeDeployDeploymentGRoup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      ServiceRoleArn: !GetAtt codedeployRole.Arn
      DeploymentConfigName: CodeDeployDefault.OneAtATime
      DeploymentGroupName: GithubActions
      Ec2TagFilters: 
        - Key:  name
          Type: KEY_AND_VALUE
          Value: PernAppInstance
#output GithubOIDC trust-relationship Arn for reference and github-oidc-Role Arn
Outputs:
  CDRole:
    Value: !Ref codedeployRole
  IdArn:
    Value: !Ref GitHubOIDC
  IamRoleArnforOIDC:
    Value: !Ref AssignIamRoleToOIDC
      
    
      


