version: '3.8'

services:
  web-app:
    image: web-app
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: on-failure
  
  api:
    image: api
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./server/.env
    restart: on-failure
