
on: workflow_dispatch

jobs:

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      content: read

    step:
      -uses: actions/checkout@V4

      -uses: aws-actions/configure-aws-credentials@v3
       with:
        role-to-assume: ${{secrets.AWS_ROLE_ARN}}
        aws-region: ${{secrets.AWS_REGION}}
      
      run: >
        aws deploy create-deployment --application-name DeployPernApp 
        --deployment-group-name PernApp
        --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash 
        --ignore-application-stop-failures

     






